// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfidhsdsghntioeyhypp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaWRoc2RzZ2hudGlvZXloeXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzA2NTAsImV4cCI6MjA1OTcwNjY1MH0.Mkm2Gd39nswnqgB4RengfUIsoCxGXYzg9CEM3AuzRUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);